name: unit-tests
on:
  push:
    branches:
    - master
jobs:
  build-docker:
    runs-on: ubuntu-latest
    steps:
      -
        name: Checkout
        uses: actions/checkout@v2
      -
        name: Install Docker
        uses: docker/setup-buildx-action@v1
        id: buildx
        with:
          install: true
      -
        name: Build
        run: docker build -f Dockerfile.dev -t fantkolja/ci-cd-tutorial:latest .
      - 
        name: Run Tests
        uses: addnab/docker-run-action@v3
        with:
          image: fantkolja/ci-cd-tutorial:latest
          run: npm run test